### ISSUE TITLE
Mention backtracking resistance in the project summary?

### ISSUE THREAD

**Issue by lgarron** [google/randen#1]
My first thought was "why aren't other fast stream ciphers (e.g. Salsa) sufficient"?

Looks like the main qualitative motivation is backtracking resistance, which takes a dive into the README to understand. I think it would be nice to highlight at the top of the project to distinguish its goals!

**Comment by jan-wassenberg** [comment]
Hi, thanks for suggesting this :) Changed to "Fast backtracking-resistant random generator (pending publication)" - does that cover all the bases?

**Comment by lgarron** [comment]
Looks like it to me! Thanks for making the change. :-)
