### ISSUE TITLE
Why not just use rdrand?

### ISSUE THREAD

**Issue by bharat42** [google/randen#5]
https://software.intel.com/en-us/articles/intel-digital-random-number-generator-drng-software-implementation-guide

**Comment by jan-wassenberg** [comment]
Can we trust it (and CBC-MAC)?

**Comment by bharat42** [comment]
Got that, Thanks

**Comment by jedisct1** [comment]
And no, we can't https://www.phoronix.com/scan.php?page=news_item&px=AMD-CPUs-RdRand-Suspend
