### ISSUE TITLE
LICENSE file is missing a copy right

### ISSUE THREAD

**Issue by nindanaoto** [google/randen#8]
We are using randen in our Homomorphic Encryption library.
https://github.com/virtualsecureplatform/TFHEpp/tree/master/thirdparties/randen

But, your LICENSE file is missing a copyright.
https://github.com/google/randen/blob/717ced67384bde1dd371589566bbc294fc42e20a/LICENSE#L190

It may good for users to add proper information here.

**Comment by jan-wassenberg** [comment]
Thanks for letting us know!

I believe it is standard practice for Google open source projects to copy the unchanged Apache 2 license text and put the copyright in the license header at the start of every source file. Is that sufficient for your needs?

**Comment by nindanaoto** [comment]
Oh, I didn't know that. If you think preserving the license and copyright notice at the start of every source file is enough to use this library, I have no problem.

Thank you for your quick reply.

**Comment by jan-wassenberg** [comment]
You're welcome :)
